<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1b0254eba2b84b9ed5bcd8bc1e7ebf22
{
    public static $files = array (
        'fb9cd3423d045f424ae879c8d11fbdcf' => __DIR__ . '/..' . '/jdlxt/easy-plugin/source/autoload.php',
    );

    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'TheSeal\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'TheSeal\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1b0254eba2b84b9ed5bcd8bc1e7ebf22::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1b0254eba2b84b9ed5bcd8bc1e7ebf22::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1b0254eba2b84b9ed5bcd8bc1e7ebf22::$classMap;

        }, null, ClassLoader::class);
    }
}
