<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'fb9cd3423d045f424ae879c8d11fbdcf' => $vendorDir . '/jdlxt/easy-plugin/source/autoload.php',
);
